version : '3.9'

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress://var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build : ./requirements/wordpress
    dockerfile: Dockerfile
    depends_on :configs:
      - mariadb
    restart: on-failure
    expose:
      - 9000




# services:
#   nginx:
#     container_name: nginx
#     build: ./requirements/nginx
#     image: img_nginx
#     volumes:
#       - wordpress-volume:/var/www/html
#     networks:
#       - inception
#     env_file:
#       - .env
#     ports:
#       - 443:443
#     restart: unless-stopped

#   mariadb:
#     container_name: mariadb
#     build: ./requirements/mariadb
#     image: mariadb
#     expose:
#       - 3306
#     volumes:
#       - db:/var/lib/mysql
#     networks:
#       - inception
#     env_file:
#       - .env
#     restart: unless-stopped

#   wordpress:
#     container_name: wordpress
#     depends_on:
#       - mariadb
#     build: ./requirements/wordpress
#     image: wordpress
#     expose:
#       - 9000
#     volumes:
#       - wordpress-volume:/var/www/html
#     networks:
#       - inception
#     env_file:
#       - .env
#     restart: unless-stopped
