version : '3'

volumes :
  wordpress:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/lchan/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/lchan/data/mariadb
      # /home/lchan/data/mariadb

networks:
  inception:
    driver: bridge

services:
  nginx:
    container_name: nginx
    env_file: .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - 443:443
    restart: on-failure

  mariadb:
    container_name: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    expose:
      - 3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    env_file: .env
    build :
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on :
      - mariadb
    restart: on-failure
    expose:
      - 9000


# services:
#   nginx:
#     container_name: nginx
#     build: ./requirements/nginx
#     image: img_nginx
#     volumes:
#       - wordpress-volume:/var/www/html
#     networks:
#       - inception
#     env_file:
#       - .env
#     ports:
#       - 443:443
#     restart: unless-stopped

#   mariadb:
#     container_name: mariadb
#     build: ./requirements/mariadb
#     image: mariadb
#     expose:
#       - 3306
#     volumes:
#       - db:/var/lib/mysql
#     networks:
#       - inception
#     env_file:
#       - .env
#     restart: unless-stopped

#   wordpress:
#     container_name: wordpress
#     depends_on:
#       - mariadb
#     build: ./requirements/wordpress
#     image: wordpress
#     expose:
#       - 9000
#     volumes:
#       - wordpress-volume:/var/www/html
#     networks:
#       - inception
#     env_file:
#       - .env
#     restart: unless-stopped
